"""initial schema

Revision ID: c03170a03cb8
Revises: 
Create Date: 2026-05-13 23:26:25.785708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c03170a03cb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='macrohero_new'
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), server_default='New chat', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['macrohero_new.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='macrohero_new'
    )
    op.create_index(op.f('ix_macrohero_new_chat_sessions_updated_at'), 'chat_sessions', ['updated_at'], unique=False, schema='macrohero_new')
    op.create_index(op.f('ix_macrohero_new_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False, schema='macrohero_new')
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('reasoning', sa.Text(), server_default='', nullable=False),
    sa.Column('actions_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('parts_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['macrohero_new.chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_chat_messages_session_ordinal'),
    schema='macrohero_new'
    )
    op.create_index(op.f('ix_macrohero_new_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False, schema='macrohero_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macrohero_new_chat_messages_session_id'), table_name='chat_messages', schema='macrohero_new')
    op.drop_table('chat_messages', schema='macrohero_new')
    op.drop_index(op.f('ix_macrohero_new_chat_sessions_user_id'), table_name='chat_sessions', schema='macrohero_new')
    op.drop_index(op.f('ix_macrohero_new_chat_sessions_updated_at'), table_name='chat_sessions', schema='macrohero_new')
    op.drop_table('chat_sessions', schema='macrohero_new')
    op.drop_table('users', schema='macrohero_new')
    # ### end Alembic commands ###
