/**
 * Codegen: fetch the factor universe from apps/numerics and write
 * packages/shared/src/factors.gen.ts.
 *
 * Run:
 *   1. Start the numerics service:
 *        cd apps/numerics && MASSIVE_API_KEY=$MASSIVE_API_KEY uv run uvicorn numerics.main:app --port 8001
 *   2. From repo root:  pnpm gen:factors
 *
 * The output file is committed to git. CI should re-run this and fail on diff
 * to catch drift between Python's FACTOR_UNIVERSE and the TS enum.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const NUMERICS_URL = process.env.NUMERICS_URL ?? "http://localhost:8001";

interface FactorResponse {
  factors: Array<{
    name: string;
    massive_ticker: string;
    asset_class: string;
    description: string;
    transform: string;
  }>;
}

async function main(): Promise<void> {
  const url = `${NUMERICS_URL}/v1/factors`;
  let res: Response;
  try {
    res = await fetch(url);
  } catch (err) {
    console.error(`Failed to reach ${url}: ${err}`);
    console.error("Is apps/numerics running on the expected port?");
    process.exit(1);
  }

  if (!res.ok) {
    console.error(`${url} returned HTTP ${res.status}`);
    process.exit(1);
  }

  const data = (await res.json()) as FactorResponse;
  if (!data.factors || !Array.isArray(data.factors) || data.factors.length === 0) {
    console.error("Empty or malformed /v1/factors response");
    process.exit(1);
  }

  const names = data.factors.map((f) => f.name);
  const namesTuple = names.map((n) => `  ${JSON.stringify(n)}`).join(",\n");

  const fileContent = `// This file is auto-generated by packages/shared/scripts/gen-factors.ts
// Do not edit manually. Re-run \`pnpm gen:factors\` to refresh.
// Source: apps/numerics GET /v1/factors

export const FACTOR_NAMES = [
${namesTuple},
] as const;

export type FactorName = (typeof FACTOR_NAMES)[number];
`;

  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "src", "factors.gen.ts");
  writeFileSync(outPath, fileContent, "utf8");

  console.log(`Wrote ${names.length} factor names to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
